export const POPULAR_SUPERMARKETS = [
  { name: "ALDI", domain: "aldi-sued.de" },
  { name: "LIDL", domain: "lidl.de" },
  { name: "REWE", domain: "rewe.de" },
  { name: "EDEKA", domain: "edeka.de" },
  { name: "Netto", domain: "netto-online.de" },
  { name: "Penny", domain: "penny.de" },
  { name: "Kaufland", domain: "kaufland.de" },
  { name: "Real", domain: "real.de" },
  { name: "Globus", domain: "globus.de" },
  { name: "HIT", domain: "hit.de" },
  { name: "Norma", domain: "norma-online.de" },
  { name: "Tegut", domain: "tegut.de" },
  { name: "Metro", domain: "metro.de" },
  { name: "Marktkauf", domain: "marktkauf.de" },
  { name: "Famila", domain: "famila.de" },
  { name: "Combi", domain: "combi.de" },
  { name: "Wasgau", domain: "wasgau.de" },
  { name: "V-Markt", domain: "v-markt.de" },
  { name: "Feneberg", domain: "feneberg.de" },
  { name: "Konsum", domain: "konsum.de" },
] as const;
